### ISSUE TITLE
Not able to create Aurora Serverless v2  writer instance with multiAz enabled

### ISSUE THREAD

**Issue by anuj1366** [terraform-aws-modules/terraform-aws-rds-aurora#312] opened 2022-08-17 17:03 UTC
## Description

I am trying to run the below terraform script to create Auora serverless v2 cluster with multiaz enabled, but somehow for me its not getting enabled.

If your request is for a new feature, please use the `Feature request` template.

- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Terraform version:
   Terraform v1.2.3
- Provider version(s):
aws v4.19.0

## Reproduction Code [Required]

```
resource "aws_db_subnet_group" "subnet_group" {
  name        = "aurora-mysql8-db-subnet-group-${var.env}"
  description = "aurora-mysql8-db-subnet-group-${var.env}"
  subnet_ids  = var.subnet_ids
  tags = merge(
    var.common_tags,
    {
      Name ="aurora-mysql8-db-subnet-group-${var.env}",
      environment = var.env
    }
  )
}


resource "aws_rds_cluster_parameter_group" "aurora-mysql8" {
  name        = "aurora-mysql8-cluster-parameter-group-${var.env}"
  family      = "aurora-mysql8.0"
  description = "aurora-mysql8-cluster-parameter-group-${var.env}"

  dynamic "parameter" {
    for_each = var.cluster_parameters
    content {
      name         = parameter.value["name"]
      value        = parameter.value["value"]
      apply_method = parameter.value["apply_method"]
    }
  }

  tags = merge(
    var.common_tags,
    {
      Name ="aurora-mysql8-cluster-parameter-group-${var.env}",
      environment = var.env
    }
  )
}


resource "aws_db_parameter_group" "aurora-mysql8" {
  name        = "aurora-mysql8-db-parameter-group-${var.env}"
  family      = "aurora-mysql8.0"
  description = "aurora-mysql8-db-parameter-group-${var.env}"
  
  dynamic "parameter" {
    for_each = var.db_parameters
    content {
      name         = parameter.value["name"]
      value        = parameter.value["value"]
      apply_method = parameter.value["apply_method"]
    }
  }

  tags = merge(
    var.common_tags,
    {
      Name ="aurora-mysql8-db-parameter-group-${var.env}",
      environment = var.env
    }
  )
}


resource "aws_rds_cluster" "aurora_serverless_v2" {
  cluster_identifier                = "tsi-rds-security-dashboard-${var.env}"
  engine                            = var.engine
  engine_version                    = var.engine_version
  master_username                   = var.master_username
  master_password                   = var.master_password
  engine_mode                       = var.engine_mode
  availability_zones                = var.availability_zones
  storage_encrypted                 = var.storage_encrypted
  deletion_protection               = var.deletion_protection
  backup_retention_period           = var.backup_retention_period
  copy_tags_to_snapshot             = var.copy_tags_to_snapshot
  db_instance_parameter_group_name  = aws_db_parameter_group.aurora-mysql8.id
  db_cluster_parameter_group_name   = aws_rds_cluster_parameter_group.aurora-mysql8.id
  db_subnet_group_name              = aws_db_subnet_group.subnet_group.name
  enable_http_endpoint              = var.enable_http_endpoint
  preferred_maintenance_window      = var.preferred_maintenance_window
  enabled_cloudwatch_logs_exports   = var.enabled_cloudwatch_logs_exports
  vpc_security_group_ids            = [var.security_group]
  skip_final_snapshot               = var.skip_final_snapshot
  apply_immediately                 = true
  final_snapshot_identifier         = "tsi-rds-security-dashboard-${var.env}-${element(concat(random_id.snapshot_identifier.*.hex, [""]), 0)}"
  
  serverlessv2_scaling_configuration {
    max_capacity = var.max_capacity
    min_capacity = var.min_capacity
  }

  tags = merge(var.common_tags,{Name = "tsi-rds-security-dashboard-dev-${var.env}",environment = var.env})
  depends_on = [
    aws_db_parameter_group.aurora-mysql8,
    aws_rds_cluster_parameter_group.aurora-mysql8,
    aws_db_subnet_group.subnet_group
  ]

}


resource "aws_rds_cluster_instance" "aurora_serverless_v2" {
  identifier                     = "tsi-rds-security-dashboard-${var.env}-instance"
  cluster_identifier             = aws_rds_cluster.aurora_serverless_v2.id
  instance_class                 = var.instance_class
  engine                         = var.engine
  engine_version                 = var.engine_version
  db_parameter_group_name        = aws_db_parameter_group.aurora-mysql8.id
  tags                           = merge(var.common_tags,{Name = aws_rds_cluster.aurora_serverless_v2.id,environment = var.env})
}


resource "random_id" "snapshot_identifier" {
  keepers = {
    id = "random"
  }
  byte_length = 4
}


Variable.tf 

module "Aurora_Serverless_V2" {
  source            = "./modules/rds"
  subnet_ids        = data.terraform_remote_state.unified_vpc.outputs.private_subnet_id
  env               = var.ENV
  common_tags       = var.common_tags
  vpc_id            =  data.terraform_remote_state.unified_vpc.outputs.vpc_id
  cluster_parameters = [
    {
      name         = "tls_version"
      value        = "TLSv1.2"
      apply_method = "pending-reboot"
    },
    {
      name         = "require_secure_transport"
      value        = "ON"
      apply_method = "immediate"
    },
    {
      name         = "general_log"
      value        = 1
      apply_method = "immediate"
    },
    {
      name         = "server_audit_logging"
      value        = 1
      apply_method = "immediate"
    },
    {
      name         = "safe-user-create"
      value        = 1
      apply_method = "pending-reboot"
    },
    {
      name         = "ssl_cipher"
      value        = "ECDHE-RSA-AES128-SHA,ECDHE-RSA-AES128-SHA256,ECDHE-RSA-AES128-GCM-SHA256,ECDHE-RSA-AES256-SHA,ECDHE-RSA-AES256-SHA384,ECDHE-RSA-AES256-GCM-SHA384"
      apply_method = "pending-reboot"
    }
  ]
  db_parameters = [
    {
      name         = "local_infile"
      value        = 0
      apply_method = "immediate"
    },
    {
      name         = "skip_show_database"
      value        = 1
      apply_method = "pending-reboot"
    },
    {
      name         = "general_log"
      value        = 1
      apply_method = "immediate"
    },
    {
      name         = "safe-user-create"
      value        = 1
      apply_method = "pending-reboot"
    }
  ]
  engine = "aurora-mysql"
  engine_version = "8.0.mysql_aurora.3.02.0"
  engine_mode = "provisioned"
  storage_encrypted = true
  deletion_protection = true
  backup_retention_period = 30
  copy_tags_to_snapshot = true
  enable_http_endpoint = false
  preferred_maintenance_window = "wed:12:00-wed:12:30"
  max_capacity = 8.0
  min_capacity = 0.5
  availability_zones = ["${data.aws_region.current.name}a", "${data.aws_region.current.name}b", "${data.aws_region.current.name}c"]
  master_username = "tsi_dashboard_admin"
  master_password = "6%3%Gd%123"
  enabled_cloudwatch_logs_exports = ["audit","error","general"]
  instance_class = "db.serverless"
  skip_final_snapshot = false
  security_group = "sg-1234567890"
}
```

**Comment by antonbabenko** [comment] 2022-08-17 17:20
Please check the code in the `examples/serverless` and I tend to close this issue as "can't reproduce" because examples and module work.

**Closed by antonbabenko** 2022-08-17 17:20 UTC

**Comment by Flame239** [comment] 2023-01-09 17:42
For people who have the same problem:
There is no parameter to enable `multi-AZ`, it is achieved by adding reader instances.
For example: if we have only 1 instance in the cluster (writer), then it shows `No` in `Multi-AZ` column, if we have 2 instanaces (writer + reader), it will show `2 Zones` meaning that we have instance in different AZs and Multi-AZ is achieved.
